// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v3.21.12
// source: proto/payment/payment.proto

package payment

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	PaymentService_FetchEventsToArchive_FullMethodName = "/payment.PaymentService/FetchEventsToArchive"
	PaymentService_DeleteArchivedEvents_FullMethodName = "/payment.PaymentService/DeleteArchivedEvents"
)

// PaymentServiceClient is the client API for PaymentService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type PaymentServiceClient interface {
	FetchEventsToArchive(ctx context.Context, in *FetchEventsToArchiveRequest, opts ...grpc.CallOption) (*FetchEventsToArchiveResponse, error)
	DeleteArchivedEvents(ctx context.Context, in *DeleteArchivedEventsRequest, opts ...grpc.CallOption) (*DeleteArchivedEventsResponse, error)
}

type paymentServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewPaymentServiceClient(cc grpc.ClientConnInterface) PaymentServiceClient {
	return &paymentServiceClient{cc}
}

func (c *paymentServiceClient) FetchEventsToArchive(ctx context.Context, in *FetchEventsToArchiveRequest, opts ...grpc.CallOption) (*FetchEventsToArchiveResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(FetchEventsToArchiveResponse)
	err := c.cc.Invoke(ctx, PaymentService_FetchEventsToArchive_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *paymentServiceClient) DeleteArchivedEvents(ctx context.Context, in *DeleteArchivedEventsRequest, opts ...grpc.CallOption) (*DeleteArchivedEventsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteArchivedEventsResponse)
	err := c.cc.Invoke(ctx, PaymentService_DeleteArchivedEvents_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PaymentServiceServer is the server API for PaymentService service.
// All implementations must embed UnimplementedPaymentServiceServer
// for forward compatibility.
type PaymentServiceServer interface {
	FetchEventsToArchive(context.Context, *FetchEventsToArchiveRequest) (*FetchEventsToArchiveResponse, error)
	DeleteArchivedEvents(context.Context, *DeleteArchivedEventsRequest) (*DeleteArchivedEventsResponse, error)
	mustEmbedUnimplementedPaymentServiceServer()
}

// UnimplementedPaymentServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedPaymentServiceServer struct{}

func (UnimplementedPaymentServiceServer) FetchEventsToArchive(context.Context, *FetchEventsToArchiveRequest) (*FetchEventsToArchiveResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method FetchEventsToArchive not implemented")
}
func (UnimplementedPaymentServiceServer) DeleteArchivedEvents(context.Context, *DeleteArchivedEventsRequest) (*DeleteArchivedEventsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteArchivedEvents not implemented")
}
func (UnimplementedPaymentServiceServer) mustEmbedUnimplementedPaymentServiceServer() {}
func (UnimplementedPaymentServiceServer) testEmbeddedByValue()                        {}

// UnsafePaymentServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to PaymentServiceServer will
// result in compilation errors.
type UnsafePaymentServiceServer interface {
	mustEmbedUnimplementedPaymentServiceServer()
}

func RegisterPaymentServiceServer(s grpc.ServiceRegistrar, srv PaymentServiceServer) {
	// If the following call panics, it indicates UnimplementedPaymentServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&PaymentService_ServiceDesc, srv)
}

func _PaymentService_FetchEventsToArchive_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FetchEventsToArchiveRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PaymentServiceServer).FetchEventsToArchive(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PaymentService_FetchEventsToArchive_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PaymentServiceServer).FetchEventsToArchive(ctx, req.(*FetchEventsToArchiveRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PaymentService_DeleteArchivedEvents_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteArchivedEventsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PaymentServiceServer).DeleteArchivedEvents(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PaymentService_DeleteArchivedEvents_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PaymentServiceServer).DeleteArchivedEvents(ctx, req.(*DeleteArchivedEventsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// PaymentService_ServiceDesc is the grpc.ServiceDesc for PaymentService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var PaymentService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "payment.PaymentService",
	HandlerType: (*PaymentServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "FetchEventsToArchive",
			Handler:    _PaymentService_FetchEventsToArchive_Handler,
		},
		{
			MethodName: "DeleteArchivedEvents",
			Handler:    _PaymentService_DeleteArchivedEvents_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/payment/payment.proto",
}
