// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v3.21.12
// source: proto/payment/payment.proto

package payment

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type OutboxEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	EventType     string                 `protobuf:"bytes,2,opt,name=event_type,json=eventType,proto3" json:"event_type,omitempty"`
	Payload       string                 `protobuf:"bytes,3,opt,name=payload,proto3" json:"payload,omitempty"`
	Status        string                 `protobuf:"bytes,4,opt,name=status,proto3" json:"status,omitempty"`
	CreatedAt     string                 `protobuf:"bytes,5,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OutboxEvent) Reset() {
	*x = OutboxEvent{}
	mi := &file_proto_payment_payment_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OutboxEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OutboxEvent) ProtoMessage() {}

func (x *OutboxEvent) ProtoReflect() protoreflect.Message {
	mi := &file_proto_payment_payment_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OutboxEvent.ProtoReflect.Descriptor instead.
func (*OutboxEvent) Descriptor() ([]byte, []int) {
	return file_proto_payment_payment_proto_rawDescGZIP(), []int{0}
}

func (x *OutboxEvent) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *OutboxEvent) GetEventType() string {
	if x != nil {
		return x.EventType
	}
	return ""
}

func (x *OutboxEvent) GetPayload() string {
	if x != nil {
		return x.Payload
	}
	return ""
}

func (x *OutboxEvent) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *OutboxEvent) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

type FetchEventsToArchiveRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MinAgeSeconds int64                  `protobuf:"varint,1,opt,name=min_age_seconds,json=minAgeSeconds,proto3" json:"min_age_seconds,omitempty"`
	Limit         int32                  `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FetchEventsToArchiveRequest) Reset() {
	*x = FetchEventsToArchiveRequest{}
	mi := &file_proto_payment_payment_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FetchEventsToArchiveRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FetchEventsToArchiveRequest) ProtoMessage() {}

func (x *FetchEventsToArchiveRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_payment_payment_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FetchEventsToArchiveRequest.ProtoReflect.Descriptor instead.
func (*FetchEventsToArchiveRequest) Descriptor() ([]byte, []int) {
	return file_proto_payment_payment_proto_rawDescGZIP(), []int{1}
}

func (x *FetchEventsToArchiveRequest) GetMinAgeSeconds() int64 {
	if x != nil {
		return x.MinAgeSeconds
	}
	return 0
}

func (x *FetchEventsToArchiveRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

type FetchEventsToArchiveResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Events        []*OutboxEvent         `protobuf:"bytes,1,rep,name=events,proto3" json:"events,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FetchEventsToArchiveResponse) Reset() {
	*x = FetchEventsToArchiveResponse{}
	mi := &file_proto_payment_payment_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FetchEventsToArchiveResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FetchEventsToArchiveResponse) ProtoMessage() {}

func (x *FetchEventsToArchiveResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_payment_payment_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FetchEventsToArchiveResponse.ProtoReflect.Descriptor instead.
func (*FetchEventsToArchiveResponse) Descriptor() ([]byte, []int) {
	return file_proto_payment_payment_proto_rawDescGZIP(), []int{2}
}

func (x *FetchEventsToArchiveResponse) GetEvents() []*OutboxEvent {
	if x != nil {
		return x.Events
	}
	return nil
}

type DeleteArchivedEventsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ids           []string               `protobuf:"bytes,1,rep,name=ids,proto3" json:"ids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteArchivedEventsRequest) Reset() {
	*x = DeleteArchivedEventsRequest{}
	mi := &file_proto_payment_payment_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteArchivedEventsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteArchivedEventsRequest) ProtoMessage() {}

func (x *DeleteArchivedEventsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_payment_payment_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteArchivedEventsRequest.ProtoReflect.Descriptor instead.
func (*DeleteArchivedEventsRequest) Descriptor() ([]byte, []int) {
	return file_proto_payment_payment_proto_rawDescGZIP(), []int{3}
}

func (x *DeleteArchivedEventsRequest) GetIds() []string {
	if x != nil {
		return x.Ids
	}
	return nil
}

type DeleteArchivedEventsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteArchivedEventsResponse) Reset() {
	*x = DeleteArchivedEventsResponse{}
	mi := &file_proto_payment_payment_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteArchivedEventsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteArchivedEventsResponse) ProtoMessage() {}

func (x *DeleteArchivedEventsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_payment_payment_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteArchivedEventsResponse.ProtoReflect.Descriptor instead.
func (*DeleteArchivedEventsResponse) Descriptor() ([]byte, []int) {
	return file_proto_payment_payment_proto_rawDescGZIP(), []int{4}
}

func (x *DeleteArchivedEventsResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *DeleteArchivedEventsResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

var File_proto_payment_payment_proto protoreflect.FileDescriptor

const file_proto_payment_payment_proto_rawDesc = "" +
	"\n" +
	"\x1bproto/payment/payment.proto\x12\apayment\"\x8d\x01\n" +
	"\vOutboxEvent\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1d\n" +
	"\n" +
	"event_type\x18\x02 \x01(\tR\teventType\x12\x18\n" +
	"\apayload\x18\x03 \x01(\tR\apayload\x12\x16\n" +
	"\x06status\x18\x04 \x01(\tR\x06status\x12\x1d\n" +
	"\n" +
	"created_at\x18\x05 \x01(\tR\tcreatedAt\"[\n" +
	"\x1bFetchEventsToArchiveRequest\x12&\n" +
	"\x0fmin_age_seconds\x18\x01 \x01(\x03R\rminAgeSeconds\x12\x14\n" +
	"\x05limit\x18\x02 \x01(\x05R\x05limit\"L\n" +
	"\x1cFetchEventsToArchiveResponse\x12,\n" +
	"\x06events\x18\x01 \x03(\v2\x14.payment.OutboxEventR\x06events\"/\n" +
	"\x1bDeleteArchivedEventsRequest\x12\x10\n" +
	"\x03ids\x18\x01 \x03(\tR\x03ids\"N\n" +
	"\x1cDeleteArchivedEventsResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error2\xda\x01\n" +
	"\x0ePaymentService\x12c\n" +
	"\x14FetchEventsToArchive\x12$.payment.FetchEventsToArchiveRequest\x1a%.payment.FetchEventsToArchiveResponse\x12c\n" +
	"\x14DeleteArchivedEvents\x12$.payment.DeleteArchivedEventsRequest\x1a%.payment.DeleteArchivedEventsResponseBKZIgithub.com/bashocode/gowallet/microservices/payment-service/proto/paymentb\x06proto3"

var (
	file_proto_payment_payment_proto_rawDescOnce sync.Once
	file_proto_payment_payment_proto_rawDescData []byte
)

func file_proto_payment_payment_proto_rawDescGZIP() []byte {
	file_proto_payment_payment_proto_rawDescOnce.Do(func() {
		file_proto_payment_payment_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_payment_payment_proto_rawDesc), len(file_proto_payment_payment_proto_rawDesc)))
	})
	return file_proto_payment_payment_proto_rawDescData
}

var file_proto_payment_payment_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_proto_payment_payment_proto_goTypes = []any{
	(*OutboxEvent)(nil),                  // 0: payment.OutboxEvent
	(*FetchEventsToArchiveRequest)(nil),  // 1: payment.FetchEventsToArchiveRequest
	(*FetchEventsToArchiveResponse)(nil), // 2: payment.FetchEventsToArchiveResponse
	(*DeleteArchivedEventsRequest)(nil),  // 3: payment.DeleteArchivedEventsRequest
	(*DeleteArchivedEventsResponse)(nil), // 4: payment.DeleteArchivedEventsResponse
}
var file_proto_payment_payment_proto_depIdxs = []int32{
	0, // 0: payment.FetchEventsToArchiveResponse.events:type_name -> payment.OutboxEvent
	1, // 1: payment.PaymentService.FetchEventsToArchive:input_type -> payment.FetchEventsToArchiveRequest
	3, // 2: payment.PaymentService.DeleteArchivedEvents:input_type -> payment.DeleteArchivedEventsRequest
	2, // 3: payment.PaymentService.FetchEventsToArchive:output_type -> payment.FetchEventsToArchiveResponse
	4, // 4: payment.PaymentService.DeleteArchivedEvents:output_type -> payment.DeleteArchivedEventsResponse
	3, // [3:5] is the sub-list for method output_type
	1, // [1:3] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_proto_payment_payment_proto_init() }
func file_proto_payment_payment_proto_init() {
	if File_proto_payment_payment_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_payment_payment_proto_rawDesc), len(file_proto_payment_payment_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_payment_payment_proto_goTypes,
		DependencyIndexes: file_proto_payment_payment_proto_depIdxs,
		MessageInfos:      file_proto_payment_payment_proto_msgTypes,
	}.Build()
	File_proto_payment_payment_proto = out.File
	file_proto_payment_payment_proto_goTypes = nil
	file_proto_payment_payment_proto_depIdxs = nil
}
