basePath: /api/v1
definitions:
  errors.AppError:
    properties:
      code:
        type: string
      message:
        type: string
    type: object
  model.CreateUserRequest:
    properties:
      email:
        description: Email bắt buộc và phải đúng định dạng email chuẩn.
        type: string
      full_name:
        description: Họ tên bắt buộc phải có
        type: string
      password:
        description: Password bắt buộc và phải có ít nhất 6 ký tự.
        minLength: 6
        type: string
    required:
    - email
    - full_name
    - password
    type: object
  model.LoginRequest:
    properties:
      email:
        example: phongluong3366@gmail.com
        type: string
      password:
        example: "123456"
        type: string
    required:
    - email
    - password
    type: object
  model.User:
    properties:
      created_at:
        type: string
      deleted_at:
        type: string
      email:
        type: string
      full_name:
        type: string
      id:
        type: string
      updated_at:
        type: string
    type: object
host: localhost:8080
info:
  contact:
    email: phongluong3366@gmail.com
    name: Phong Luong
  description: API Documentation for GoWallet Monolith
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  termsOfService: http://swagger.io/terms/
  title: GoWallet Monolith API
  version: "1.0"
paths:
  /users/{id}:
    get:
      consumes:
      - application/json
      description: Get user profile by user ID
      parameters:
      - description: user id (uuid)
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/model.User'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/errors.AppError'
      summary: Get User Profile
      tags:
      - Users
  /users/login:
    post:
      consumes:
      - application/json
      description: Authenticate user and return JWT token
      parameters:
      - description: login payload
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/model.LoginRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties: true
            type: object
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/errors.AppError'
      summary: User Login
      tags:
      - Users
  /users/register:
    post:
      consumes:
      - application/json
      description: Create new User with default wallet
      parameters:
      - description: register user payload
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/model.CreateUserRequest'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/model.User'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/errors.AppError'
        "409":
          description: Conflict
          schema:
            $ref: '#/definitions/errors.AppError'
      summary: Register New User
      tags:
      - Users
swagger: "2.0"
