// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v7.35.1
// source: proto/transaction/transaction.proto

package transaction

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type TopUpRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	UserId         string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Amount         string                 `protobuf:"bytes,2,opt,name=amount,proto3" json:"amount,omitempty"` // decimal as string, e.g. "10.00"
	IdempotencyKey string                 `protobuf:"bytes,3,opt,name=idempotency_key,json=idempotencyKey,proto3" json:"idempotency_key,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *TopUpRequest) Reset() {
	*x = TopUpRequest{}
	mi := &file_proto_transaction_transaction_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TopUpRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TopUpRequest) ProtoMessage() {}

func (x *TopUpRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_transaction_transaction_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TopUpRequest.ProtoReflect.Descriptor instead.
func (*TopUpRequest) Descriptor() ([]byte, []int) {
	return file_proto_transaction_transaction_proto_rawDescGZIP(), []int{0}
}

func (x *TopUpRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *TopUpRequest) GetAmount() string {
	if x != nil {
		return x.Amount
	}
	return ""
}

func (x *TopUpRequest) GetIdempotencyKey() string {
	if x != nil {
		return x.IdempotencyKey
	}
	return ""
}

type TopUpResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TransactionId string                 `protobuf:"bytes,1,opt,name=transaction_id,json=transactionId,proto3" json:"transaction_id,omitempty"`
	Status        string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TopUpResponse) Reset() {
	*x = TopUpResponse{}
	mi := &file_proto_transaction_transaction_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TopUpResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TopUpResponse) ProtoMessage() {}

func (x *TopUpResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_transaction_transaction_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TopUpResponse.ProtoReflect.Descriptor instead.
func (*TopUpResponse) Descriptor() ([]byte, []int) {
	return file_proto_transaction_transaction_proto_rawDescGZIP(), []int{1}
}

func (x *TopUpResponse) GetTransactionId() string {
	if x != nil {
		return x.TransactionId
	}
	return ""
}

func (x *TopUpResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

var File_proto_transaction_transaction_proto protoreflect.FileDescriptor

const file_proto_transaction_transaction_proto_rawDesc = "" +
	"\n" +
	"#proto/transaction/transaction.proto\x12\vtransaction\"h\n" +
	"\fTopUpRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x16\n" +
	"\x06amount\x18\x02 \x01(\tR\x06amount\x12'\n" +
	"\x0fidempotency_key\x18\x03 \x01(\tR\x0eidempotencyKey\"N\n" +
	"\rTopUpResponse\x12%\n" +
	"\x0etransaction_id\x18\x01 \x01(\tR\rtransactionId\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status2T\n" +
	"\x12TransactionService\x12>\n" +
	"\x05TopUp\x12\x19.transaction.TopUpRequest\x1a\x1a.transaction.TopUpResponseBSZQgithub.com/bashocode/gowallet/microservices/transaction-service/proto/transactionb\x06proto3"

var (
	file_proto_transaction_transaction_proto_rawDescOnce sync.Once
	file_proto_transaction_transaction_proto_rawDescData []byte
)

func file_proto_transaction_transaction_proto_rawDescGZIP() []byte {
	file_proto_transaction_transaction_proto_rawDescOnce.Do(func() {
		file_proto_transaction_transaction_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_transaction_transaction_proto_rawDesc), len(file_proto_transaction_transaction_proto_rawDesc)))
	})
	return file_proto_transaction_transaction_proto_rawDescData
}

var file_proto_transaction_transaction_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_proto_transaction_transaction_proto_goTypes = []any{
	(*TopUpRequest)(nil),  // 0: transaction.TopUpRequest
	(*TopUpResponse)(nil), // 1: transaction.TopUpResponse
}
var file_proto_transaction_transaction_proto_depIdxs = []int32{
	0, // 0: transaction.TransactionService.TopUp:input_type -> transaction.TopUpRequest
	1, // 1: transaction.TransactionService.TopUp:output_type -> transaction.TopUpResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_transaction_transaction_proto_init() }
func file_proto_transaction_transaction_proto_init() {
	if File_proto_transaction_transaction_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_transaction_transaction_proto_rawDesc), len(file_proto_transaction_transaction_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_transaction_transaction_proto_goTypes,
		DependencyIndexes: file_proto_transaction_transaction_proto_depIdxs,
		MessageInfos:      file_proto_transaction_transaction_proto_msgTypes,
	}.Build()
	File_proto_transaction_transaction_proto = out.File
	file_proto_transaction_transaction_proto_goTypes = nil
	file_proto_transaction_transaction_proto_depIdxs = nil
}
