version: "3.8"

services:
  mysql:
    image: mysql:8.0
    container_name: gowallet-mysql
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: gowallet
      MYSQL_USER: gowallet_user
      MYSQL_PASSWORD: gowallet_password
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    restart: always

volumes:
  mysql_data:
    name: gowallet_mysql_fixed_data
