// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v3.21.12
// source: proto/ledger/ledger.proto

package ledger

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RecordEntryRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TransactionId string                 `protobuf:"bytes,1,opt,name=transaction_id,json=transactionId,proto3" json:"transaction_id,omitempty"` // Mã giao dịch gốc (field number = 1)
	WalletId      string                 `protobuf:"bytes,2,opt,name=wallet_id,json=walletId,proto3" json:"wallet_id,omitempty"`                // Mã ví thực hiện (field number = 2)
	Type          string                 `protobuf:"bytes,3,opt,name=type,proto3" json:"type,omitempty"`                                        // credit or debit (loại giao dịch: cộng hoặc trừ tiền)
	Amount        string                 `protobuf:"bytes,4,opt,name=amount,proto3" json:"amount,omitempty"`                                    // decimal as string, e.g. "10000.50" (số tiền dạng chuỗi để tránh sai số float)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RecordEntryRequest) Reset() {
	*x = RecordEntryRequest{}
	mi := &file_proto_ledger_ledger_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RecordEntryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RecordEntryRequest) ProtoMessage() {}

func (x *RecordEntryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ledger_ledger_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RecordEntryRequest.ProtoReflect.Descriptor instead.
func (*RecordEntryRequest) Descriptor() ([]byte, []int) {
	return file_proto_ledger_ledger_proto_rawDescGZIP(), []int{0}
}

func (x *RecordEntryRequest) GetTransactionId() string {
	if x != nil {
		return x.TransactionId
	}
	return ""
}

func (x *RecordEntryRequest) GetWalletId() string {
	if x != nil {
		return x.WalletId
	}
	return ""
}

func (x *RecordEntryRequest) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *RecordEntryRequest) GetAmount() string {
	if x != nil {
		return x.Amount
	}
	return ""
}

type RecordEntryResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EntryId       string                 `protobuf:"bytes,1,opt,name=entry_id,json=entryId,proto3" json:"entry_id,omitempty"` // Mã định danh bản ghi sổ cái vừa tạo
	Success       bool                   `protobuf:"varint,2,opt,name=success,proto3" json:"success,omitempty"`               // Trạng thái thành công hay thất bại
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RecordEntryResponse) Reset() {
	*x = RecordEntryResponse{}
	mi := &file_proto_ledger_ledger_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RecordEntryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RecordEntryResponse) ProtoMessage() {}

func (x *RecordEntryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ledger_ledger_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RecordEntryResponse.ProtoReflect.Descriptor instead.
func (*RecordEntryResponse) Descriptor() ([]byte, []int) {
	return file_proto_ledger_ledger_proto_rawDescGZIP(), []int{1}
}

func (x *RecordEntryResponse) GetEntryId() string {
	if x != nil {
		return x.EntryId
	}
	return ""
}

func (x *RecordEntryResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type RecordEntriesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Entries       []*RecordEntryRequest  `protobuf:"bytes,1,rep,name=entries,proto3" json:"entries,omitempty"` // Mảng danh sách các yêu cầu ghi bút toán
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RecordEntriesRequest) Reset() {
	*x = RecordEntriesRequest{}
	mi := &file_proto_ledger_ledger_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RecordEntriesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RecordEntriesRequest) ProtoMessage() {}

func (x *RecordEntriesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ledger_ledger_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RecordEntriesRequest.ProtoReflect.Descriptor instead.
func (*RecordEntriesRequest) Descriptor() ([]byte, []int) {
	return file_proto_ledger_ledger_proto_rawDescGZIP(), []int{2}
}

func (x *RecordEntriesRequest) GetEntries() []*RecordEntryRequest {
	if x != nil {
		return x.Entries
	}
	return nil
}

type RecordEntriesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"` // Trạng thái xử lý toàn bộ lô
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RecordEntriesResponse) Reset() {
	*x = RecordEntriesResponse{}
	mi := &file_proto_ledger_ledger_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RecordEntriesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RecordEntriesResponse) ProtoMessage() {}

func (x *RecordEntriesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ledger_ledger_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RecordEntriesResponse.ProtoReflect.Descriptor instead.
func (*RecordEntriesResponse) Descriptor() ([]byte, []int) {
	return file_proto_ledger_ledger_proto_rawDescGZIP(), []int{3}
}

func (x *RecordEntriesResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type GetBalanceRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	WalletId      string                 `protobuf:"bytes,1,opt,name=wallet_id,json=walletId,proto3" json:"wallet_id,omitempty"` // Mã ví cần tra cứu số dư
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetBalanceRequest) Reset() {
	*x = GetBalanceRequest{}
	mi := &file_proto_ledger_ledger_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetBalanceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBalanceRequest) ProtoMessage() {}

func (x *GetBalanceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ledger_ledger_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBalanceRequest.ProtoReflect.Descriptor instead.
func (*GetBalanceRequest) Descriptor() ([]byte, []int) {
	return file_proto_ledger_ledger_proto_rawDescGZIP(), []int{4}
}

func (x *GetBalanceRequest) GetWalletId() string {
	if x != nil {
		return x.WalletId
	}
	return ""
}

type BalanceResponse struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	CalculatedBalance string                 `protobuf:"bytes,1,opt,name=calculated_balance,json=calculatedBalance,proto3" json:"calculated_balance,omitempty"` // Số dư hiện tại dưới dạng chuỗi độ chính xác cao
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *BalanceResponse) Reset() {
	*x = BalanceResponse{}
	mi := &file_proto_ledger_ledger_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BalanceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BalanceResponse) ProtoMessage() {}

func (x *BalanceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ledger_ledger_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BalanceResponse.ProtoReflect.Descriptor instead.
func (*BalanceResponse) Descriptor() ([]byte, []int) {
	return file_proto_ledger_ledger_proto_rawDescGZIP(), []int{5}
}

func (x *BalanceResponse) GetCalculatedBalance() string {
	if x != nil {
		return x.CalculatedBalance
	}
	return ""
}

type GetEntriesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	WalletId      string                 `protobuf:"bytes,1,opt,name=wallet_id,json=walletId,proto3" json:"wallet_id,omitempty"` // Mã ví cần truy vấn lịch sử
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetEntriesRequest) Reset() {
	*x = GetEntriesRequest{}
	mi := &file_proto_ledger_ledger_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetEntriesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetEntriesRequest) ProtoMessage() {}

func (x *GetEntriesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ledger_ledger_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetEntriesRequest.ProtoReflect.Descriptor instead.
func (*GetEntriesRequest) Descriptor() ([]byte, []int) {
	return file_proto_ledger_ledger_proto_rawDescGZIP(), []int{6}
}

func (x *GetEntriesRequest) GetWalletId() string {
	if x != nil {
		return x.WalletId
	}
	return ""
}

type EntriesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Entries       []*LedgerEntry         `protobuf:"bytes,1,rep,name=entries,proto3" json:"entries,omitempty"` // Mảng chứa các đối tượng bản ghi sổ cái chi tiết
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EntriesResponse) Reset() {
	*x = EntriesResponse{}
	mi := &file_proto_ledger_ledger_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EntriesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EntriesResponse) ProtoMessage() {}

func (x *EntriesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ledger_ledger_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EntriesResponse.ProtoReflect.Descriptor instead.
func (*EntriesResponse) Descriptor() ([]byte, []int) {
	return file_proto_ledger_ledger_proto_rawDescGZIP(), []int{7}
}

func (x *EntriesResponse) GetEntries() []*LedgerEntry {
	if x != nil {
		return x.Entries
	}
	return nil
}

type LedgerEntry struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`                                            // ID duy nhất của dòng sổ cái
	TransactionId string                 `protobuf:"bytes,2,opt,name=transaction_id,json=transactionId,proto3" json:"transaction_id,omitempty"` // Mã giao dịch liên kết
	WalletId      string                 `protobuf:"bytes,3,opt,name=wallet_id,json=walletId,proto3" json:"wallet_id,omitempty"`                // Mã ví sở hữu
	EntryType     string                 `protobuf:"bytes,4,opt,name=entry_type,json=entryType,proto3" json:"entry_type,omitempty"`             // Loại bút toán (credit/debit)
	Amount        string                 `protobuf:"bytes,5,opt,name=amount,proto3" json:"amount,omitempty"`                                    // Số tiền giao dịch
	CreatedAt     string                 `protobuf:"bytes,6,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`             // Thời điểm tạo bản ghi
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LedgerEntry) Reset() {
	*x = LedgerEntry{}
	mi := &file_proto_ledger_ledger_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LedgerEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LedgerEntry) ProtoMessage() {}

func (x *LedgerEntry) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ledger_ledger_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LedgerEntry.ProtoReflect.Descriptor instead.
func (*LedgerEntry) Descriptor() ([]byte, []int) {
	return file_proto_ledger_ledger_proto_rawDescGZIP(), []int{8}
}

func (x *LedgerEntry) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *LedgerEntry) GetTransactionId() string {
	if x != nil {
		return x.TransactionId
	}
	return ""
}

func (x *LedgerEntry) GetWalletId() string {
	if x != nil {
		return x.WalletId
	}
	return ""
}

func (x *LedgerEntry) GetEntryType() string {
	if x != nil {
		return x.EntryType
	}
	return ""
}

func (x *LedgerEntry) GetAmount() string {
	if x != nil {
		return x.Amount
	}
	return ""
}

func (x *LedgerEntry) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

var File_proto_ledger_ledger_proto protoreflect.FileDescriptor

const file_proto_ledger_ledger_proto_rawDesc = "" +
	"\n" +
	"\x19proto/ledger/ledger.proto\x12\x06ledger\"\x84\x01\n" +
	"\x12RecordEntryRequest\x12%\n" +
	"\x0etransaction_id\x18\x01 \x01(\tR\rtransactionId\x12\x1b\n" +
	"\twallet_id\x18\x02 \x01(\tR\bwalletId\x12\x12\n" +
	"\x04type\x18\x03 \x01(\tR\x04type\x12\x16\n" +
	"\x06amount\x18\x04 \x01(\tR\x06amount\"J\n" +
	"\x13RecordEntryResponse\x12\x19\n" +
	"\bentry_id\x18\x01 \x01(\tR\aentryId\x12\x18\n" +
	"\asuccess\x18\x02 \x01(\bR\asuccess\"L\n" +
	"\x14RecordEntriesRequest\x124\n" +
	"\aentries\x18\x01 \x03(\v2\x1a.ledger.RecordEntryRequestR\aentries\"1\n" +
	"\x15RecordEntriesResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"0\n" +
	"\x11GetBalanceRequest\x12\x1b\n" +
	"\twallet_id\x18\x01 \x01(\tR\bwalletId\"@\n" +
	"\x0fBalanceResponse\x12-\n" +
	"\x12calculated_balance\x18\x01 \x01(\tR\x11calculatedBalance\"0\n" +
	"\x11GetEntriesRequest\x12\x1b\n" +
	"\twallet_id\x18\x01 \x01(\tR\bwalletId\"@\n" +
	"\x0fEntriesResponse\x12-\n" +
	"\aentries\x18\x01 \x03(\v2\x13.ledger.LedgerEntryR\aentries\"\xb7\x01\n" +
	"\vLedgerEntry\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12%\n" +
	"\x0etransaction_id\x18\x02 \x01(\tR\rtransactionId\x12\x1b\n" +
	"\twallet_id\x18\x03 \x01(\tR\bwalletId\x12\x1d\n" +
	"\n" +
	"entry_type\x18\x04 \x01(\tR\tentryType\x12\x16\n" +
	"\x06amount\x18\x05 \x01(\tR\x06amount\x12\x1d\n" +
	"\n" +
	"created_at\x18\x06 \x01(\tR\tcreatedAt2\xc9\x02\n" +
	"\rLedgerService\x12L\n" +
	"\x11RecordLedgerEntry\x12\x1a.ledger.RecordEntryRequest\x1a\x1b.ledger.RecordEntryResponse\x12R\n" +
	"\x13RecordLedgerEntries\x12\x1c.ledger.RecordEntriesRequest\x1a\x1d.ledger.RecordEntriesResponse\x12J\n" +
	"\x14GetBalanceFromLedger\x12\x19.ledger.GetBalanceRequest\x1a\x17.ledger.BalanceResponse\x12J\n" +
	"\x14GetEntriesByWalletID\x12\x19.ledger.GetEntriesRequest\x1a\x17.ledger.EntriesResponseBIZGgithub.com/bashocode/gowallet/microservices/ledger-service/proto/ledgerb\x06proto3"

var (
	file_proto_ledger_ledger_proto_rawDescOnce sync.Once
	file_proto_ledger_ledger_proto_rawDescData []byte
)

func file_proto_ledger_ledger_proto_rawDescGZIP() []byte {
	file_proto_ledger_ledger_proto_rawDescOnce.Do(func() {
		file_proto_ledger_ledger_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_ledger_ledger_proto_rawDesc), len(file_proto_ledger_ledger_proto_rawDesc)))
	})
	return file_proto_ledger_ledger_proto_rawDescData
}

var file_proto_ledger_ledger_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_proto_ledger_ledger_proto_goTypes = []any{
	(*RecordEntryRequest)(nil),    // 0: ledger.RecordEntryRequest
	(*RecordEntryResponse)(nil),   // 1: ledger.RecordEntryResponse
	(*RecordEntriesRequest)(nil),  // 2: ledger.RecordEntriesRequest
	(*RecordEntriesResponse)(nil), // 3: ledger.RecordEntriesResponse
	(*GetBalanceRequest)(nil),     // 4: ledger.GetBalanceRequest
	(*BalanceResponse)(nil),       // 5: ledger.BalanceResponse
	(*GetEntriesRequest)(nil),     // 6: ledger.GetEntriesRequest
	(*EntriesResponse)(nil),       // 7: ledger.EntriesResponse
	(*LedgerEntry)(nil),           // 8: ledger.LedgerEntry
}
var file_proto_ledger_ledger_proto_depIdxs = []int32{
	0, // 0: ledger.RecordEntriesRequest.entries:type_name -> ledger.RecordEntryRequest
	8, // 1: ledger.EntriesResponse.entries:type_name -> ledger.LedgerEntry
	0, // 2: ledger.LedgerService.RecordLedgerEntry:input_type -> ledger.RecordEntryRequest
	2, // 3: ledger.LedgerService.RecordLedgerEntries:input_type -> ledger.RecordEntriesRequest
	4, // 4: ledger.LedgerService.GetBalanceFromLedger:input_type -> ledger.GetBalanceRequest
	6, // 5: ledger.LedgerService.GetEntriesByWalletID:input_type -> ledger.GetEntriesRequest
	1, // 6: ledger.LedgerService.RecordLedgerEntry:output_type -> ledger.RecordEntryResponse
	3, // 7: ledger.LedgerService.RecordLedgerEntries:output_type -> ledger.RecordEntriesResponse
	5, // 8: ledger.LedgerService.GetBalanceFromLedger:output_type -> ledger.BalanceResponse
	7, // 9: ledger.LedgerService.GetEntriesByWalletID:output_type -> ledger.EntriesResponse
	6, // [6:10] is the sub-list for method output_type
	2, // [2:6] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_proto_ledger_ledger_proto_init() }
func file_proto_ledger_ledger_proto_init() {
	if File_proto_ledger_ledger_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_ledger_ledger_proto_rawDesc), len(file_proto_ledger_ledger_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_ledger_ledger_proto_goTypes,
		DependencyIndexes: file_proto_ledger_ledger_proto_depIdxs,
		MessageInfos:      file_proto_ledger_ledger_proto_msgTypes,
	}.Build()
	File_proto_ledger_ledger_proto = out.File
	file_proto_ledger_ledger_proto_goTypes = nil
	file_proto_ledger_ledger_proto_depIdxs = nil
}
