// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v7.35.1
// source: proto/ledger/ledger.proto

package ledger

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	LedgerService_RecordLedgerEntry_FullMethodName    = "/ledger.LedgerService/RecordLedgerEntry"
	LedgerService_RecordLedgerEntries_FullMethodName  = "/ledger.LedgerService/RecordLedgerEntries"
	LedgerService_GetBalanceFromLedger_FullMethodName = "/ledger.LedgerService/GetBalanceFromLedger"
	LedgerService_GetEntriesByWalletID_FullMethodName = "/ledger.LedgerService/GetEntriesByWalletID"
)

// LedgerServiceClient is the client API for LedgerService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type LedgerServiceClient interface {
	RecordLedgerEntry(ctx context.Context, in *RecordEntryRequest, opts ...grpc.CallOption) (*RecordEntryResponse, error)
	RecordLedgerEntries(ctx context.Context, in *RecordEntriesRequest, opts ...grpc.CallOption) (*RecordEntriesResponse, error)
	GetBalanceFromLedger(ctx context.Context, in *GetBalanceRequest, opts ...grpc.CallOption) (*BalanceResponse, error)
	GetEntriesByWalletID(ctx context.Context, in *GetEntriesRequest, opts ...grpc.CallOption) (*EntriesResponse, error)
}

type ledgerServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewLedgerServiceClient(cc grpc.ClientConnInterface) LedgerServiceClient {
	return &ledgerServiceClient{cc}
}

func (c *ledgerServiceClient) RecordLedgerEntry(ctx context.Context, in *RecordEntryRequest, opts ...grpc.CallOption) (*RecordEntryResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RecordEntryResponse)
	err := c.cc.Invoke(ctx, LedgerService_RecordLedgerEntry_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *ledgerServiceClient) RecordLedgerEntries(ctx context.Context, in *RecordEntriesRequest, opts ...grpc.CallOption) (*RecordEntriesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RecordEntriesResponse)
	err := c.cc.Invoke(ctx, LedgerService_RecordLedgerEntries_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *ledgerServiceClient) GetBalanceFromLedger(ctx context.Context, in *GetBalanceRequest, opts ...grpc.CallOption) (*BalanceResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BalanceResponse)
	err := c.cc.Invoke(ctx, LedgerService_GetBalanceFromLedger_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *ledgerServiceClient) GetEntriesByWalletID(ctx context.Context, in *GetEntriesRequest, opts ...grpc.CallOption) (*EntriesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(EntriesResponse)
	err := c.cc.Invoke(ctx, LedgerService_GetEntriesByWalletID_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// LedgerServiceServer is the server API for LedgerService service.
// All implementations must embed UnimplementedLedgerServiceServer
// for forward compatibility.
type LedgerServiceServer interface {
	RecordLedgerEntry(context.Context, *RecordEntryRequest) (*RecordEntryResponse, error)
	RecordLedgerEntries(context.Context, *RecordEntriesRequest) (*RecordEntriesResponse, error)
	GetBalanceFromLedger(context.Context, *GetBalanceRequest) (*BalanceResponse, error)
	GetEntriesByWalletID(context.Context, *GetEntriesRequest) (*EntriesResponse, error)
	mustEmbedUnimplementedLedgerServiceServer()
}

// UnimplementedLedgerServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedLedgerServiceServer struct{}

func (UnimplementedLedgerServiceServer) RecordLedgerEntry(context.Context, *RecordEntryRequest) (*RecordEntryResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RecordLedgerEntry not implemented")
}
func (UnimplementedLedgerServiceServer) RecordLedgerEntries(context.Context, *RecordEntriesRequest) (*RecordEntriesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RecordLedgerEntries not implemented")
}
func (UnimplementedLedgerServiceServer) GetBalanceFromLedger(context.Context, *GetBalanceRequest) (*BalanceResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetBalanceFromLedger not implemented")
}
func (UnimplementedLedgerServiceServer) GetEntriesByWalletID(context.Context, *GetEntriesRequest) (*EntriesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetEntriesByWalletID not implemented")
}
func (UnimplementedLedgerServiceServer) mustEmbedUnimplementedLedgerServiceServer() {}
func (UnimplementedLedgerServiceServer) testEmbeddedByValue()                       {}

// UnsafeLedgerServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to LedgerServiceServer will
// result in compilation errors.
type UnsafeLedgerServiceServer interface {
	mustEmbedUnimplementedLedgerServiceServer()
}

func RegisterLedgerServiceServer(s grpc.ServiceRegistrar, srv LedgerServiceServer) {
	// If the following call panics, it indicates UnimplementedLedgerServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&LedgerService_ServiceDesc, srv)
}

func _LedgerService_RecordLedgerEntry_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RecordEntryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LedgerServiceServer).RecordLedgerEntry(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LedgerService_RecordLedgerEntry_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LedgerServiceServer).RecordLedgerEntry(ctx, req.(*RecordEntryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LedgerService_RecordLedgerEntries_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RecordEntriesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LedgerServiceServer).RecordLedgerEntries(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LedgerService_RecordLedgerEntries_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LedgerServiceServer).RecordLedgerEntries(ctx, req.(*RecordEntriesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LedgerService_GetBalanceFromLedger_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetBalanceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LedgerServiceServer).GetBalanceFromLedger(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LedgerService_GetBalanceFromLedger_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LedgerServiceServer).GetBalanceFromLedger(ctx, req.(*GetBalanceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LedgerService_GetEntriesByWalletID_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetEntriesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LedgerServiceServer).GetEntriesByWalletID(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LedgerService_GetEntriesByWalletID_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LedgerServiceServer).GetEntriesByWalletID(ctx, req.(*GetEntriesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// LedgerService_ServiceDesc is the grpc.ServiceDesc for LedgerService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var LedgerService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "ledger.LedgerService",
	HandlerType: (*LedgerServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "RecordLedgerEntry",
			Handler:    _LedgerService_RecordLedgerEntry_Handler,
		},
		{
			MethodName: "RecordLedgerEntries",
			Handler:    _LedgerService_RecordLedgerEntries_Handler,
		},
		{
			MethodName: "GetBalanceFromLedger",
			Handler:    _LedgerService_GetBalanceFromLedger_Handler,
		},
		{
			MethodName: "GetEntriesByWalletID",
			Handler:    _LedgerService_GetEntriesByWalletID_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/ledger/ledger.proto",
}
