package scheduler

import (
	"os"
	"path/filepath"
	"testing"
	"time"

	"github.com/DATA-DOG/go-sqlmock"
	ledgerRepo "github.com/bashocode/gowallet/monolith/internal/ledger/repository"
	"github.com/bashocode/gowallet/monolith/internal/logger"
	walletRepo "github.com/bashocode/gowallet/monolith/internal/wallet/repository"
	"github.com/shopspring/decimal"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/mock"
)

func init() {
	logger.InitLogger()
}

func TestSchedulerStartStop(t *testing.T) {
	db, _, err := sqlmock.New()
	assert.NoError(t, err)
	defer db.Close()

	wRepo := &walletRepo.MockWalletRepository{}
	lRepo := &ledgerRepo.MockLedgerRepository{}

	s := NewScheduler(db, wRepo, lRepo)
	assert.NotNil(t, s)

	s.Start()
	s.Stop()
}

func TestCleanupExpiredOTPs(t *testing.T) {
	db, sMock, err := sqlmock.New()
	assert.NoError(t, err)
	defer db.Close()

	wRepo := &walletRepo.MockWalletRepository{}
	lRepo := &ledgerRepo.MockLedgerRepository{}
	s := NewScheduler(db, wRepo, lRepo)

	sMock.ExpectExec("DELETE FROM otp_codes WHERE expires_at < NOW()").
		WillReturnResult(sqlmock.NewResult(0, 5))

	s.CleanupExpiredOTPs()
}

func TestReconcileAllBalances(t *testing.T) {
	db, sMock, err := sqlmock.New()
	assert.NoError(t, err)
	defer db.Close()

	wRepo := &walletRepo.MockWalletRepository{}
	lRepo := &ledgerRepo.MockLedgerRepository{}
	s := NewScheduler(db, wRepo, lRepo)

	rows := sqlmock.NewRows([]string{"id", "user_id", "balance"}).
		AddRow("w1", "user1", "100.00").
		AddRow("w2", "user2", "200.00")
	sMock.ExpectQuery("SELECT id, user_id, balance FROM wallets").WillReturnRows(rows)

	lRepo.On("GetBalanceByWalletID", mock.Anything, "w1").Return(decimal.NewFromInt(100), nil)
	lRepo.On("GetBalanceByWalletID", mock.Anything, "w2").Return(decimal.NewFromInt(150), nil) // Mismatch!

	s.ReconcileAllBalances()

	lRepo.AssertExpectations(t)
}

func TestCleanupExpiredRefreshTokens(t *testing.T) {
	db, sMock, err := sqlmock.New()
	assert.NoError(t, err)
	defer db.Close()

	wRepo := &walletRepo.MockWalletRepository{}
	lRepo := &ledgerRepo.MockLedgerRepository{}
	s := NewScheduler(db, wRepo, lRepo)

	sMock.ExpectExec("DELETE FROM refresh_tokens WHERE expires_at < NOW()").
		WillReturnResult(sqlmock.NewResult(0, 10))

	s.CleanupExpiredRefreshTokens()
}

func TestExportDailyTransactions(t *testing.T) {
	db, sMock, err := sqlmock.New()
	assert.NoError(t, err)
	defer db.Close()

	wRepo := &walletRepo.MockWalletRepository{}
	lRepo := &ledgerRepo.MockLedgerRepository{}
	s := NewScheduler(db, wRepo, lRepo)

	now := time.Now().Format("2006-01-02 15:04:05")
	rows := sqlmock.NewRows([]string{"id", "sender_wallet_id", "receiver_wallet_id", "amount", "status", "created_at"}).
		AddRow("tx1", "w1", "w2", "50.00", "SUCCESS", now).
		AddRow("tx2", nil, "w2", "100.00", "SUCCESS", now)

	sMock.ExpectQuery("SELECT").WillReturnRows(rows)

	s.ExportDailyTransactions()

	// Clean up report files generated by the test
	filename := filepath.Join(
		"./reports",
		"transaction_report_"+time.Now().Format("20060102")+".csv",
	)
	_ = os.Remove(filename)
}
