
input {
  tcp {
    port => "${LOGSTASH_PORT:5000}"
    codec => json_lines
  }
}

filter {
  if [time] {
    date {
      match => [ "time", "ISO8601" ]
      target => "@timestamp"
      remove_field => [ "time" ]
    }
  }
}

output {
  elasticsearch {
    hosts => ["http://elasticsearch:${ELASTICSEARCH_PORT:9200}"]
    index => "gowallet-logs-%{+YYYY.MM.dd}"
  }
  stdout {
    codec => rubydebug
  }
}